ILLUMINA_INSTRUMENT_MODEL: set[str] = {
    "Illumina Genome Analyzer",
    "Illumina Genome Analyzer II",
    "Illumina Genome Analyzer IIx",
    "Illumina HiSeq 2500",
    "Illumina HiSeq 2000",
    "Illumina HiSeq 1500",
    "Illumina HiSeq 1000",
    "Illumina HiSeq X",
    "Illumina MiSeq",
    "Illumina HiScanSQ",
    "Illumina iSeq 100",
    "HiSeq X Ten",
    "NextSeq 500",
    "HiSeq X Five",
    "Illumina HiSeq 3000",
    "Illumina HiSeq 4000",
    "NextSeq 550",
    "NextSeq 1000",
    "NextSeq 2000",
    "Illumina NovaSeq 6000",
    "Illumina NovaSeq X",
    "Illumina NovaSeq X Plus",
    "Illumina MiniSeq",
    "Illumina MiSeq i100",
    "Illumina MiSeq i100 Plus"
}

ILLUMINA_LIBRARY_SOURCE: set[str] = {
    "GENOMIC",
    "TRANSCRIPTOMIC",
    "METAGENOMIC",
    "METATRANSCRIPTOMIC",
    "SYNTHETIC",
    "VIRAL RNA",
    "GENOMIC SINGLE CELL",
    "TRANSCRIPTOMIC SINGLE CELL",
    "OTHER"
}

ILLUMINA_LIBRARY_SELECTION: set[str] = {
    "RANDOM",
    "PCR",
    "RANDOM PCR",
    "RT-PCR",
    "HMPR",
    "MF",
    "CF-S",
    "CF-M",
    "CF-H",
    "CF-T",
    "MDA",
    "MSLL",
    "cDNA",
    "ChIP",
    "MNase",
    "DNAse",
    "Hybrid Selection",
    "Reduced Representation",
    "Restriction Digest",
    "5-methylcytidine antibody",
    "MBD2 protein methyl-CpG binding domain",
    "CAGE",
    "RACE",
    "size fractionation",
    "Padlock probes capture method",
    "other",
    "unspecified",
    "cDNA_oligo_dT",
    "cDNA_randomPriming",
    "Inverse rRNA",
    "Oligo-dT",
    "PolyA",
    "repeat fractionation"
}

ILLUMNINA_LIBARY_LAYOUT: set[str] = {"single", "paired"}

ILLUMINA_LIBRARY_STRATEGY: set[str] = {
    "WGS",
    "WGA",
    "WXS",
    "RNA-Seq",
    "ssRNA-seq",
    "miRNA-Seq",
    "ncRNA-Seq",
    "FL-cDNA",
    "EST",
    "Hi-C",
    "ATAC-seq",
    "WCS",
    "RAD-Seq",
    "CLONE",
    "POOLCLONE",
    "AMPLICON",
    "CLONEEND",
    "FINISHING",
    "ChIP-Seq",
    "MNase-Seq",
    "DNase-Hypersensitivity",
    "Bisulfite-Seq",
    "CTS",
    "MRE-Seq",
    "MeDIP-Seq",
    "DIP-Seq",
    "MBD-Seq",
    "Tn-Seq",
    "VALIDATION",
    "FAIRE-seq",
    "SELEX",
    "NOMe-Seq",
    "RIP-Seq",
    "ChIA-PET",
    "Synthetic-Long-Read",
    "Targeted-Capture",
    "Tethered Chromatin Conformation Capture",
    "OTHER"
}

BS_HOST_SEX: set[str] = {
    "male",
    "female",
    "pooled male and female",
    "neuter",
    "hermaphrodite",
    "intersex",
    "not determined",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_SOURCE_TYPE: set[str] = {"human", "animal", "food", "environmental", "other"}

OHE_BUILDING_SETTING: set[str] = {
    "urban",
    "suburban",
    "exurban",
    "rural",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_ENV_MONITORING_ZONE: set[str] = {
    "Zone 1",
    "Zone 2",
    "Zone 3",
    "Zone 4",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_INDOOR_SURFACE: set[str] = {
    "counter top",
    "window",
    "wall",
    "cabinet",
    "ceiling",
    "door",
    "shelving",
    "vent cover",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_INTENDED_CONSUMER: set[str] = {
    "human as food consumer",
    "animal as food consumer",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_SPEC_INTENDED_CONS: set[str] = {
    "animal as food consumer",
    "laboratory animal as food consumer",
    "non-food animal as food consumer",
    "pet animal as consumer",
    "pet fish as consumer",
    "pet cat as consumer",
    "pet bird as consumer",
    "pet dog as consumer",
    "sheep or goat as consumer",
    "food animal as consumer",
    "food fish as consumer",
    "poultry as consumer",
    "pig as consumer",
    "game as consumer",
    "rabbit as consumer",
    "cattle as consumer",
    "horse as consumer",
    "human as food consumer",
    "adult human as food consumer",
    "man as food consumer",
    "woman as food consumer",
    "senior as food consumer",
    "athlete as food consumer",
    "bodybuilder as food consumer",
    "weight-reducer as food consumer",
    "human as food consumer, four years and above",
    "teenager as food consumer",
    "child as food consumer, less than four years",
    "infant or toddler as food consumer",
    "toddler as food consumer, 12 months and onwards",
    "infant as food consumer",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

OHE_SURF_MATERIAL: set[str] = {
    "concrete",
    "wood",
    "stone",
    "tile",
    "plastic",
    "glass",
    "vinyl",
    "metal",
    "carpet",
    "stainless steel",
    "paint",
    "cinder blocks",
    "hay bales",
    "stucco",
    "adobe",
    "missing",
    "not applicable",
    "not collected",
    "not provided",
    "restricted access"
}

COUNTRY: set[str] = {
    # from https://www.insdc.org/submitting-standards/geo_loc_name-qualifier-vocabulary/
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Arctic Ocean",
    "Argentina",
    "Armenia",
    "Aruba",
    "Ashmore and Cartier Islands",
    "Atlantic Ocean",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Baltic Sea",
    "Baker Island",
    "Bangladesh",
    "Barbados",
    "Bassas da India",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Borneo",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Clipperton Island",
    "Cocos Islands",
    "Colombia",
    "Comoros",
    "Cook Islands",
    "Coral Sea Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czechia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Europa Island",
    "Falkland Islands (Islas Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern and Antarctic Lands",
    "Gabon",
    "Gambia",
    "Gaza Strip",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Glorioso Islands",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Hong Kong",
    "Howland Island",
    "Hungary",
    "Iceland",
    "India",
    "Indian Ocean",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Jan Mayen",
    "Japan",
    "Jarvis Island",
    "Jersey",
    "Johnston Atoll",
    "Jordan",
    "Juan de Nova Island",
    "Kazakhstan",
    "Kenya",
    "Kerguelen Archipelago",
    "Kingman Reef",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Line Islands",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mediterranean Sea",
    "Mexico",
    "Micronesia, Federated States of",
    "Midway Islands",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Navassa Island",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "North Sea",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pacific Ocean",
    "Pakistan",
    "Palau",
    "Palmyra Atoll",
    "Panama",
    "Papua New Guinea",
    "Paracel Islands",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of the Congo",
    "Reunion",
    "Romania",
    "Ross Sea",
    "Russia",
    "Rwanda",
    "Saint Barthelemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Southern Ocean",
    "Spain",
    "Spratly Islands",
    "Sri Lanka",
    "State of Palestine",
    "Sudan",
    "Suriname",
    "Svalbard",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Tasman Sea",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tromelin Island",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "USA",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Virgin Islands",
    "Wake Island",
    "Wallis and Futuna",
    "West Bank",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
}
